name: CI/CD - Build

on: 
  push:
    branches:
      - main
     pull_request:
        branches:
          - main
jobs: 
  build:
    name:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout do repositório
          uses: actions/checkout@v4
          
        - name: Configuração Java 21
          uses: actions/setup-java@v4
          with: 
            
            java-version: '21'
            distribution: 'temurin'
            cache: maven
            
          - name: Build da aplicação
            run: mvn clean packge -DskipTest
            
        - name: Salvar
          uses: action/upload-artifact@v4
             whith:
                name: app-war
                path: target/*.war
                retention-day: 7 
